In [2]:
import numpy as np
import pandas as pd

In [3]:
rd1day_1 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_1_day_-1_wn.csv",delimiter = ';')
rd1day_2 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_1_day_-2_wn.csv",delimiter = ';')
rd1day0 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_1_day_0_wn.csv",delimiter = ';')
rd2day0 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_3_day_0_wn.csv",delimiter = ';')
rd2day1 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_3_day_1_wn.csv",delimiter = ';')
rd2day2 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_3_day_2_wn.csv",delimiter = ';')
rd3day_1 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_4_day_1_wn.csv",delimiter = ';')
rd3day2 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_4_day_2_wn.csv",delimiter = ';')
rd3day3 = pd.read_csv("/Users/aayushmishra/Desktop/IMCProsperity/Data/round-5-island-data-bottle/trades_round_4_day_3_wn.csv",delimiter = ';')
tradesall = pd.concat([rd1day_1,rd1day_2,rd1day0,rd2day0,rd2day1,rd2day2,rd3day_1,rd3day2,rd3day3], ignore_index=True)

In [4]:
tradesall.head(20)

    timestamp      buyer     seller     symbol   currency    price  quantity
0           0     Amelia  Valentina  STARFRUIT  SEASHELLS   5047.0        13
1           0       Remy  Valentina  STARFRUIT  SEASHELLS   5047.0         1
2           0       Remy     Vinnie  AMETHYSTS  SEASHELLS  10004.0         1
3        1100     Vinnie     Amelia  AMETHYSTS  SEASHELLS   9996.0         2
4        1700       Remy   Vladimir  AMETHYSTS  SEASHELLS  10002.0         1
5        1700       Ruby   Vladimir  STARFRUIT  SEASHELLS   5043.0         8
6        1800       Remy  Valentina  AMETHYSTS  SEASHELLS  10002.0         1
7        1900       Remy   Vladimir  STARFRUIT  SEASHELLS   5044.0         1
8        2000  Valentina       Remy  AMETHYSTS  SEASHELLS   9998.0         1
9        2400  Valentina       Remy  STARFRUIT  SEASHELLS   5038.0         1
10       2900     Vinnie     Amelia  AMETHYSTS  SEASHELLS   9996.0         1
11       2900  Valentina     Amelia  AMETHYSTS  SEASHELLS   9996.0        11
12       3000       Remy  Valentina  AMETHYSTS  SEASHELLS  10005.0         1
13       3000       Remy  Valentina  STARFRUIT  SEASHELLS   5045.0         1
14       3100     Vinnie       Remy  AMETHYSTS  SEASHELLS   9996.0         2
15       3100  Valentina       Remy  STARFRUIT  SEASHELLS   5037.0         2
16       3200  Valentina       Remy  STARFRUIT  SEASHELLS   5037.0         1
17       3200     Vinnie       Remy  AMETHYSTS  SEASHELLS   9996.0         1
18       3200     Vinnie       Remy  STARFRUIT  SEASHELLS   5037.0         1
19       3200  Valentina       Remy  AMETHYSTS  SEASHELLS   9996.0         1

In [5]:
tradesall['buyer'].value_counts()

Vinnie       9648
Remy         8620
Valentina    7488
Vladimir     2227
Ruby         1760
Rhianna      1694
Amelia        641
Adam          363
Raj           210
Name: buyer, dtype: int64

In [6]:
tradesall['seller'].value_counts()

Remy         9164
Vinnie       8915
Valentina    5044
Vladimir     3927
Rhianna      2396
Ruby         1964
Amelia        627
Adam          393
Raj           221
Name: seller, dtype: int64

In [7]:
Starfruit_trades = tradesall[tradesall['symbol'] == "STARFRUIT"]
Amethyst_trades = tradesall[tradesall['symbol'] == "AMETHYSTS"]
Giftbasket_trades = tradesall[tradesall['symbol'] == "GIFT_BASKET"]
Chocolate_trades = tradesall[tradesall['symbol'] == "CHOCOLATE"]
Strawberries_trades = tradesall[tradesall['symbol'] == "STRAWBERRIES"]
Rose_trades = tradesall[tradesall['symbol'] == "ROSES"]
Coconut_trades = tradesall[tradesall['symbol'] == "COCONUT"]
Coupon_trades = tradesall[tradesall['symbol'] == "COCONUT_COUPON"]

In [8]:
Coupon_trades['buyer'].value_counts()

Valentina    2531
Ruby          380
Vladimir      214
Vinnie         25
Rhianna        10
Name: buyer, dtype: int64

In [9]:
Coupon_trades['seller'].value_counts()

Vinnie       1623
Valentina     671
Ruby          439
Rhianna       388
Vladimir       39
Name: seller, dtype: int64

In [10]:
Coconut_trades['buyer'].value_counts()

Vinnie     1578
Raj         210
Rhianna     181
Name: buyer, dtype: int64

In [11]:
Coconut_trades['seller'].value_counts()

Vinnie     1551
Raj         221
Rhianna     197
Name: seller, dtype: int64

In [12]:
Giftbasket_trades['buyer'].value_counts()

Vinnie      558
Vladimir    464
Ruby        385
Rhianna     358
Name: buyer, dtype: int64

In [13]:
Giftbasket_trades['seller'].value_counts()

Rhianna     592
Vinnie      486
Ruby        403
Vladimir    284
Name: seller, dtype: int64

In [14]:
Chocolate_trades['buyer'].value_counts()

Vinnie      1768
Remy        1077
Vladimir       3
Name: buyer, dtype: int64

In [47]:
Chocolate_trades['seller'].value_counts()

Remy        1188
Vinnie      1071
Vladimir     589
Name: seller, dtype: int64

In [15]:
Strawberries_trades['buyer'].value_counts()

Vinnie      2400
Remy        1247
Vladimir       7
Name: buyer, dtype: int64

In [16]:
Strawberries_trades['seller'].value_counts()

Vinnie      1234
Remy        1228
Vladimir    1192
Name: seller, dtype: int64

In [17]:
Rose_trades['buyer'].value_counts()

Vinnie      1687
Remy        1413
Rhianna        3
Vladimir       2
Name: buyer, dtype: int64

In [18]:
Rose_trades['seller'].value_counts()

Vinnie      1415
Remy        1376
Vladimir     311
Rhianna        3
Name: seller, dtype: int64

In [19]:
Amethyst_trades['buyer'].value_counts()

Remy         2197
Valentina    1739
Vinnie        949
Vladimir      753
Rhianna       655
Ruby          509
Amelia        302
Adam          131
Name: buyer, dtype: int64

In [20]:
Amethyst_trades['seller'].value_counts()

Remy         2182
Valentina    1725
Vinnie        906
Vladimir      697
Rhianna       677
Ruby          604
Amelia        302
Adam          142
Name: seller, dtype: int64

In [21]:
Starfruit_trades['buyer'].value_counts()

Valentina    3218
Remy         2686
Vladimir      784
Vinnie        683
Rhianna       487
Ruby          486
Amelia        339
Adam          232
Name: buyer, dtype: int64

In [22]:
Starfruit_trades['seller'].value_counts()

Remy         3190
Valentina    2648
Vladimir      815
Vinnie        629
Rhianna       539
Ruby          518
Amelia        325
Adam          251
Name: seller, dtype: int64

In [26]:
tradesall.sort_values(by='quantity', ascending=False).head(60)

,timestamp,buyer,seller,symbol,currency,price,quantity
31971,580800,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,536.0,20
28807,749600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,671.0,20
30062,458500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,657.0,20
32229,734800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,581.0,20
27711,99700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,592.0,20
32213,725100,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,584.0,20
28322,452200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,677.0,20
28323,452200,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,678.0,20
30821,933300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,663.0,20
32203,719900,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,583.0,20
30798,921800,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,657.0,20
28799,746000,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,658.0,20
29842,335200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,673.0,20
30139,502300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,664.0,20
32190,708300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,573.0,20
27690,88500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,593.0,20
30153,511100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,670.0,20
31780,472700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,581.0,20
32177,705200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,584.0,20
30772,901600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,635.0,20
30757,890800,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,618.0,20
31808,484500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,590.0,20
30845,946300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,671.0,20
30035,442000,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,685.0,20
31712,433500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,582.0,20
32243,742800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,587.0,20
29851,343600,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,663.0,20
28972,848900,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,702.0,20
29855,345700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,659.0,20
30980,17600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,604.0,20
27757,130400,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,622.0,20
27748,124800,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,622.0,20
31664,404900,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,569.0,20
32291,770800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,548.0,20
29343,69600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,691.0,20
32282,765700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,568.0,20
30965,9400,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,601.0,20
28239,408000,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,664.0,20
27582,34200,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,630.0,20
30948,997100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,622.0,20
29990,414600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,702.0,20
28887,791800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,664.0,20
32258,750600,Ruby,Valentina,COCONUT_COUPON,SEASHELLS,597.0,20
28886,790300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,662.0,20
30915,981100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,617.0,20
32151,688800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,581.0,20
30219,556500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,667.0,20
32130,670300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,585.0,20
32051,618000,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,551.0,20
30575,769700,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,646.0,20
31895,534900,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,566.0,20
32045,615300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,551.0,20
27604,45700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,620.0,20
32040,613300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,554.0,20
31906,538800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,571.0,20
31910,542900,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,560.0,20
30411,666100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,634.0,20
30546,752500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,659.0,20
31919,547200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,566.0,20
30438,683600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,632.0,20

In [33]:
tradesall[tradesall["buyer"]=="Valentina"].sort_values(by ="quantity",ascending = False).head(50)

,timestamp,buyer,seller,symbol,currency,price,quantity
30640,809500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,638.0,20
30352,625600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,643.0,20
28322,452200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,677.0,20
29238,3500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,677.0,20
32504,907100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,560.0,20
31564,344100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,590.0,20
30506,723200,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,648.0,20
32083,637500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,563.0,20
29171,958800,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,681.0,20
31560,340100,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,595.0,20
29143,947300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,684.0,20
31550,334500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,598.0,20
31549,333700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,596.0,20
30546,752500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,659.0,20
32116,657200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,585.0,20
30575,769700,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,646.0,20
30582,773400,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,642.0,20
30594,781700,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,650.0,20
32477,885000,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,570.0,20
31124,97600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,597.0,20
32063,624900,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,566.0,20
30475,707300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,653.0,20
29396,102600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,736.0,20
30371,637600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,654.0,20
31968,580300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,531.0,20
31971,580800,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,536.0,20
29417,116400,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,720.0,20
29414,114500,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,731.0,20
31149,110300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,608.0,20
30411,666100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,634.0,20
29343,69600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,691.0,20
27918,224400,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,616.0,20
30438,683600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,632.0,20
29326,57000,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,686.0,20
32040,613300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,554.0,20
30448,691100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,646.0,20
32045,615300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,551.0,20
32051,618000,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,551.0,20
30454,693900,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,651.0,20
28033,291600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,654.0,20
32130,670300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,585.0,20
28041,298100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,669.0,20
30821,933300,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,663.0,20
30980,17600,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,604.0,20
32269,756200,Valentina,Ruby,COCONUT_COUPON,SEASHELLS,590.0,20
28219,396100,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,686.0,20
30965,9400,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,601.0,20
28649,655300,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,655.0,20
28239,408000,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,664.0,20
28641,649200,Valentina,Vinnie,COCONUT_COUPON,SEASHELLS,646.0,20

In [35]:
tradesall[tradesall["symbol"]=="GIFT_BASKET"].sort_values(by ="quantity",ascending = False).head(50)

,timestamp,buyer,seller,symbol,currency,price,quantity
19133,777300,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71118.0,10
23511,943100,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70761.0,10
16852,187800,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71372.0,10
22047,561300,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71034.0,10
16343,48400,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71438.0,10
22088,573900,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71073.0,10
25358,416700,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,69820.0,10
22358,640900,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70733.0,10
22371,645300,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70769.0,10
23089,830700,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70805.0,10
26560,746000,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70024.0,10
17613,384200,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71259.0,10
16478,83800,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71161.0,10
23862,37300,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70590.0,10
16855,188500,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71339.0,10
24747,264100,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70116.0,10
18367,572700,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71438.0,10
24697,249900,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70343.0,10
24021,74500,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70754.0,10
24636,232900,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70267.0,10
24085,89900,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70708.0,10
20384,98200,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70995.0,10
24131,98300,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70711.0,10
24244,134300,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70532.0,10
18037,489300,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71488.0,10
24389,169400,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70436.0,10
21566,427000,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71114.0,10
24427,179900,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70428.0,10
27418,972300,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,69683.0,10
21017,277400,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71222.0,10
20759,206600,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70819.0,10
20169,39200,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71139.0,10
20176,41200,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71126.0,10
16236,21000,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71400.0,10
25893,565100,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,69569.0,10
26044,603900,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,69550.0,10
25589,478800,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,69772.0,10
21275,344700,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70974.0,10
25714,515300,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,69773.0,10
24193,118600,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70703.0,9
23860,37000,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70578.0,9
16928,206000,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71256.0,9
24957,318100,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,69781.0,9
16244,22500,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71364.0,9
23588,966700,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70786.0,9
16526,97900,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71211.0,9
18584,626200,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,71282.0,9
23667,987400,Ruby,Vladimir,GIFT_BASKET,SEASHELLS,70579.0,9
23703,997000,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,70563.0,9
18062,497000,Vladimir,Ruby,GIFT_BASKET,SEASHELLS,71537.0,9

In [36]:
tradesall[tradesall["symbol"]=="STARFRUIT"].sort_values(by ="quantity",ascending = False).head(50)

       timestamp      buyer     seller     symbol   currency   price  quantity
13055     404700     Amelia  Valentina  STARFRUIT  SEASHELLS  5061.0        15
10903      12000    Rhianna  Valentina  STARFRUIT  SEASHELLS  5032.0        15
1550      286300  Valentina       Ruby  STARFRUIT  SEASHELLS  5028.0        15
7083      327000  Valentina     Amelia  STARFRUIT  SEASHELLS  4963.0        15
7063      323200     Amelia  Valentina  STARFRUIT  SEASHELLS  4966.0        15
12020     207800     Amelia  Valentina  STARFRUIT  SEASHELLS  5051.0        15
13317     452100  Valentina       Ruby  STARFRUIT  SEASHELLS  5053.0        15
14854     745600  Valentina       Ruby  STARFRUIT  SEASHELLS  5057.0        15
15286     829300     Amelia  Valentina  STARFRUIT  SEASHELLS  5090.0        15
3530      662200       Ruby  Valentina  STARFRUIT  SEASHELLS  5070.0        15
13689     521800       Ruby  Valentina  STARFRUIT  SEASHELLS  5070.0        15
4272      797400  Valentina       Ruby  STARFRUIT  SEASHELLS  5053.0        15
6706      251900  Valentina       Ruby  STARFRUIT  SEASHELLS  4954.0        15
2646      493700  Valentina     Amelia  STARFRUIT  SEASHELLS  5072.0        15
8693      611700  Valentina     Amelia  STARFRUIT  SEASHELLS  5010.0        15
10877       7300  Valentina     Amelia  STARFRUIT  SEASHELLS  5030.0        15
622       114800       Ruby  Valentina  STARFRUIT  SEASHELLS  5045.0        15
9084      679900     Amelia  Valentina  STARFRUIT  SEASHELLS  5033.0        15
1942      357000  Valentina     Amelia  STARFRUIT  SEASHELLS  5043.0        15
6540      223900     Amelia  Valentina  STARFRUIT  SEASHELLS  4960.0        15
14633     705200       Ruby  Valentina  STARFRUIT  SEASHELLS  5066.0        15
9157      691500       Ruby  Valentina  STARFRUIT  SEASHELLS  5032.0        15
9218      702300  Valentina       Ruby  STARFRUIT  SEASHELLS  5020.0        15
15401     854300  Valentina     Amelia  STARFRUIT  SEASHELLS  5073.0        15
12373     273400  Valentina     Amelia  STARFRUIT  SEASHELLS  5046.0        15
12388     276800  Valentina       Ruby  STARFRUIT  SEASHELLS  5045.0        15
11982     200200  Valentina       Ruby  STARFRUIT  SEASHELLS  5047.0        15
11939     192400       Ruby  Valentina  STARFRUIT  SEASHELLS  5053.0        15
6355      187600     Amelia  Valentina  STARFRUIT  SEASHELLS  4961.0        15
11254      69900       Ruby  Valentina  STARFRUIT  SEASHELLS  5041.0        15
7905      475900     Amelia  Valentina  STARFRUIT  SEASHELLS  4990.0        15
4509      840900  Valentina       Ruby  STARFRUIT  SEASHELLS  5053.0        15
13547     495200  Valentina       Ruby  STARFRUIT  SEASHELLS  5057.0        15
2011      371400  Valentina       Ruby  STARFRUIT  SEASHELLS  5043.0        15
2066      380300  Valentina       Ruby  STARFRUIT  SEASHELLS  5042.0        15
3603      672700       Ruby  Valentina  STARFRUIT  SEASHELLS  5070.0        15
300        58400  Valentina       Ruby  STARFRUIT  SEASHELLS  5029.0        15
7590      421300  Valentina       Ruby  STARFRUIT  SEASHELLS  4982.0        15
11759     156400     Amelia  Valentina  STARFRUIT  SEASHELLS  5056.0        15
2119      392900  Valentina       Ruby  STARFRUIT  SEASHELLS  5043.0        15
2141      397000     Amelia  Valentina  STARFRUIT  SEASHELLS  5053.0        15
11245      67900       Ruby  Valentina  STARFRUIT  SEASHELLS  5043.0        15
16036     979200  Valentina       Ruby  STARFRUIT  SEASHELLS  5051.0        15
15195     809600  Valentina    Rhianna  STARFRUIT  SEASHELLS  5089.0        15
8421      567200       Ruby  Valentina  STARFRUIT  SEASHELLS  5012.0        15
11208      60500  Valentina       Ruby  STARFRUIT  SEASHELLS  5037.0        15
15574     888400  Valentina       Ruby  STARFRUIT  SEASHELLS  5070.0        15
1004      187700       Ruby  Valentina  STARFRUIT  SEASHELLS  5041.0        15
11165      52600  Valentina     Amelia  STARFRUIT  SEASHELLS  5037.0        15
8533      586500       Ruby  Valentina  STARFRUIT  SEASHELLS  5018.0        15

In [37]:
tradesall[tradesall["symbol"]=="CHOCOLATE"].sort_values(by ="quantity",ascending = False).head(50)

       timestamp   buyer    seller     symbol   currency   price  quantity
21890     513000  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7936.0        10
24210     124300  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7897.0        10
25016     330900  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7763.0        10
17042     239200  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7994.0        10
24889     302200  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7771.0        10
17137     264100  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7981.0        10
24533     207200  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7850.0        10
24399     171900  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7873.0        10
24219     127300  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7898.0        10
24202     120900  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7907.0        10
25345     413900  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7783.0        10
24119      96700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7898.0        10
24084      89800  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7900.0        10
24002      71500  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7908.0        10
23960      61200  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7899.0        10
17385     326200  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8016.0        10
23775      14800  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7896.0        10
23636     979000  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7884.0        10
16949     212100  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7996.0        10
25367     420700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7787.0        10
23619     973600  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7887.0        10
26141     629800  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7751.0        10
26473     724000  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7803.0        10
26397     703400  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7782.0        10
26360     690300  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7756.0        10
26330     682500  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7748.0        10
16608     121600  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8027.0        10
26238     658100  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7734.0        10
26182     641700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7761.0        10
26039     602600  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7738.0        10
25434     436700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7770.0        10
25960     580200  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7727.0        10
25903     566900  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7733.0        10
16763     161600  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8036.0        10
25707     512300  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7741.0        10
25694     507700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7735.0        10
25692     506600  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7734.0        10
16803     173700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8023.0        10
23624     974600  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7884.0        10
23579     964000  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7894.0        10
16479      83800  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8025.0        10
19843     958500  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8020.0        10
18251     542000  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8010.0        10
20804     218300  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7960.0        10
20475     122300  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7970.0        10
18375     573900  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8025.0        10
20066      12700  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  7982.0        10
19917     975500  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8000.0        10
18542     614000  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8003.0        10
18586     626800  Vinnie  Vladimir  CHOCOLATE  SEASHELLS  8001.0        10

In [39]:
tradesall[tradesall["symbol"]=="ROSES"].sort_values(by ="quantity",ascending = False).head(50)

       timestamp   buyer    seller symbol   currency    price  quantity
24835     287800  Vinnie  Vladimir  ROSES  SEASHELLS  14327.0        11
16711     149700  Vinnie  Vladimir  ROSES  SEASHELLS  14747.0        11
25049     337900  Vinnie  Vladimir  ROSES  SEASHELLS  14295.0        11
27452     980400  Vinnie  Vladimir  ROSES  SEASHELLS  14336.0        11
20612     166000  Vinnie  Vladimir  ROSES  SEASHELLS  14537.0        11
18437     588700  Vinnie  Vladimir  ROSES  SEASHELLS  14687.0        11
23378     910300  Vinnie  Vladimir  ROSES  SEASHELLS  14440.0        11
23362     906300  Vinnie  Vladimir  ROSES  SEASHELLS  14441.0        11
27077     882800  Vinnie  Vladimir  ROSES  SEASHELLS  14296.0        11
22481     672100  Vinnie  Vladimir  ROSES  SEASHELLS  14532.0        11
25075     345000  Vinnie  Vladimir  ROSES  SEASHELLS  14260.0        11
25769     529000  Vinnie  Vladimir  ROSES  SEASHELLS  14250.0        11
21011     275900  Vinnie  Vladimir  ROSES  SEASHELLS  14567.0        11
23100     834100  Vinnie  Vladimir  ROSES  SEASHELLS  14474.0        11
18496     603700  Vinnie  Vladimir  ROSES  SEASHELLS  14716.0        11
16818     177500  Vinnie  Vladimir  ROSES  SEASHELLS  14728.0        11
20917     248300  Vinnie  Vladimir  ROSES  SEASHELLS  14485.0        11
20901     245600  Vinnie  Vladimir  ROSES  SEASHELLS  14486.0        11
18518     607600  Vinnie  Vladimir  ROSES  SEASHELLS  14734.0        11
20557     148300  Vinnie  Vladimir  ROSES  SEASHELLS  14568.0        11
20416     104600  Vinnie  Vladimir  ROSES  SEASHELLS  14600.0        11
16597     119500  Vinnie  Vladimir  ROSES  SEASHELLS  14731.0        11
26638     766600  Vinnie  Vladimir  ROSES  SEASHELLS  14375.0        11
16466      80000  Vinnie  Vladimir  ROSES  SEASHELLS  14752.0        11
25668     497700  Vinnie  Vladimir  ROSES  SEASHELLS  14255.0        11
27323     945300  Vinnie  Vladimir  ROSES  SEASHELLS  14332.0        11
19806     946500  Vinnie  Vladimir  ROSES  SEASHELLS  14457.0        11
21298     351600  Vinnie  Vladimir  ROSES  SEASHELLS  14511.0        11
18772     679200  Vinnie  Vladimir  ROSES  SEASHELLS  14585.0        11
19722     926400  Vinnie  Vladimir  ROSES  SEASHELLS  14418.0        11
22611     705900  Vinnie  Vladimir  ROSES  SEASHELLS  14625.0        10
21425     388000  Vinnie  Vladimir  ROSES  SEASHELLS  14523.0        10
20938     252200  Vinnie  Vladimir  ROSES  SEASHELLS  14480.0        10
25977     585600  Vinnie  Vladimir  ROSES  SEASHELLS  14253.0        10
21664     454900  Vinnie  Vladimir  ROSES  SEASHELLS  14519.0        10
22810     758900  Vinnie  Vladimir  ROSES  SEASHELLS  14564.0        10
22908     787500  Vinnie  Vladimir  ROSES  SEASHELLS  14530.0        10
25158     366900  Vinnie  Vladimir  ROSES  SEASHELLS  14263.0        10
27078     883000  Vinnie  Vladimir  ROSES  SEASHELLS  14297.0        10
22874     776800  Vinnie  Vladimir  ROSES  SEASHELLS  14560.0        10
18819     690900  Vinnie  Vladimir  ROSES  SEASHELLS  14577.0        10
24996     326500  Vinnie  Vladimir  ROSES  SEASHELLS  14282.0        10
24881     301000  Vinnie  Vladimir  ROSES  SEASHELLS  14273.0        10
25281     399600  Vinnie  Vladimir  ROSES  SEASHELLS  14322.0        10
25543     468700  Vinnie  Vladimir  ROSES  SEASHELLS  14328.0        10
17822     439400  Vinnie  Vladimir  ROSES  SEASHELLS  14725.0        10
19313     821200  Vinnie  Vladimir  ROSES  SEASHELLS  14559.0        10
20875     239600  Vinnie  Vladimir  ROSES  SEASHELLS  14496.0        10
20674     181900  Vinnie  Vladimir  ROSES  SEASHELLS  14476.0        10
17816     438500  Vinnie  Vladimir  ROSES  SEASHELLS  14722.0        10

In [40]:
tradesall[tradesall["symbol"]=="STRAWBERRIES"].sort_values(by ="quantity",ascending = False).head(50)

       timestamp   buyer    seller        symbol   currency   price  quantity
18501     604500  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4036.0        12
21514     412600  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4060.0        12
21113     304600  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4039.0        12
21156     314400  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4042.0        12
18640     643500  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4049.0        12
21328     359300  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4050.0        12
25749     525000  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4007.0        12
21355     367400  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4056.0        12
21397     379600  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4058.0        12
21483     403500  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4058.0        12
21645     450900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4059.0        12
18335     563500  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4043.0        12
25550     470200  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4003.0        12
21742     475900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4069.0        12
25500     457100  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4005.0        12
21772     482600  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4073.0        12
25440     438300  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4008.0        12
25439     438100  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4006.0        12
18405     581000  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4040.0        12
16945     209200  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4004.0        12
16755     160300  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3993.0        12
21093     299900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4039.0        12
25910     568400  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4012.0        12
26055     606500  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3990.0        12
26815     811600  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3988.0        12
20300      74800  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4039.0        12
20371      94900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4032.0        12
26719     785000  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3982.0        12
26663     771800  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3978.0        12
16512      95100  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3990.0        12
16562     108300  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3999.0        12
20631     171200  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4030.0        12
20687     185400  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4032.0        12
26313     676800  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3974.0        12
26267     666900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3977.0        12
18829     694800  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4043.0        12
16646     132000  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3997.0        12
26226     655700  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3983.0        12
26167     638300  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3981.0        12
20897     244900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4036.0        12
20909     247300  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4035.0        12
16962     217100  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4005.0        12
22002     551400  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4076.0        12
26883     827900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  3988.0        12
23098     833900  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4067.0        12
17926     462100  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4028.0        12
24253     135800  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4039.0        12
17872     450600  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4019.0        12
17856     447800  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4016.0        12
23048     821100  Vinnie  Vladimir  STRAWBERRIES  SEASHELLS  4079.0        12